exports.collections = [
  {
    name: "test name",
    description: "test description",
    price: "22",
    slug: "nude-arts-paint",
    nftImage: "./img/nftimage",
    files: [
      "./img/image-1",
      "./img/image-1",
      "./img/image-1",
      "./img/image-1",
      "./img/image-1",
      "./img/video-1",
      "./img/video-1",
      "./img/video-1",
      "./img/video-1",
      "./img/video-1",
      "./img/video-1",
    ],
  },
  {
    name: "test name",
    description: "test description",
    price: "22",
    slug: "nude-arts-paint",
    nftImage: "./img/nftimage",
    files: [
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
      ],
  },
  {
    name: "test name",
    description: "test description",
    price: "22",
    slug: "nude-arts-paint",
    nftImage: "./img/nftimage",
    files: [
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
      ],
  },
];
