exports.collections = [
  {
    name: "Halloween Nights",
    description: "It is a NFT to unlock my halloween theme looks.",
    price: "5",
    metadata_id: "unlockableteststore.mintspace2.testnet:035c116cc95b8a5f6eb1246aebd4bfa0",
    nftImage: "https://testnet.mintbase.io/_next/image?url=https%3A%2F%2Fimage-cache-service-z3w7d7dnea-ew.a.run.app%2Fmedia%3Furl%3Dhttps%3A%2F%2Farweave.net%2FOjUs3Q0TWCFwn7ln15mNFJGY4jL3qjYCQhoJ0tTj0G0&w=1920&q=75",
    files: [
      "./img/image-1",
      "./img/image-1",
      "./img/image-1",
      "./img/image-1",
      "./img/image-1",
      "./img/video-1",
      "./img/video-1",
      "./img/video-1",
      "./img/video-1",
      "./img/video-1",
      "./img/video-1",
    ],
  },
  {
    name: "Fun in Space",
    description: "this is a collection of videos of me having fun in space.",
    price: "89",
    nftImage: "./img/nftimage",
    files: [
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
      ],
  },
  {
    name: "Cigarette Party",
    description: "It is a NFT to unlock my content which i smoke cigarette.",
    price: "16",
    nftImage: "./img/nftimage",
    files: [
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/image-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
        "./img/video-1",
      ],
  },
];
